name: CI
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        platform: [windows-2019]
    runs-on: ${{ matrix.platform }}
    env:
      CMAKE_PRESET: windows-release
    steps:
      - name: Checkout Current Branch
        uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Run CMake
        uses: lukka/run-cmake@v10
        with:
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          configurePreset: '${{ env.CMAKE_PRESET }}'
          buildPreset: '${{ env.CMAKE_PRESET }}'
